# Generated by Django 4.2.3 on 2024-03-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience_Professionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date debut')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('entreprise', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nom de la structure')),
                ('poste', models.CharField(blank=True, max_length=50, null=True, verbose_name='Poste')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Description du poste')),
                ('pays', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pays')),
                ('ville', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville')),
                ('staut', models.CharField(blank=True, choices=[('En cours', 'En cours'), ('Terminé', 'Terminé')], max_length=30, null=True, verbose_name='Statut')),
                ('date_created', models.DateField(auto_now=True, null=True, verbose_name='date_created')),
            ],
        ),
        migrations.CreateModel(
            name='Galerie_perso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/services/', verbose_name='Image de la realisation')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name="Description de l'image")),
                ('date_created', models.DateField(auto_now=True, null=True, verbose_name='date_created')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=30, null=True, verbose_name='Prenom')),
                ('sexe', models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=10, null=True, verbose_name='Sexe')),
                ('telephone_1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telephone')),
                ('telephone_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telephone')),
                ('pays', models.CharField(blank=True, max_length=30, null=True, verbose_name='Pays')),
                ('ville', models.CharField(blank=True, max_length=30, null=True, verbose_name='ville')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='E-mail')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Date creation')),
            ],
        ),
        migrations.CreateModel(
            name='Services_proposes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=100, null=True, verbose_name='Services proposés')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description du service')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/services/', verbose_name='Image du service')),
                ('date_created', models.DateField(auto_now=True, null=True, verbose_name='date_created')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviceperso', to='Resume.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Reglage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ReglagePerso', to='Resume.personnel')),
                ('photo_couverture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couvertureperso', to='Resume.galerie_perso')),
                ('photo_profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profilperso', to='Resume.galerie_perso')),
                ('poste_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posteactuel', to='Resume.experience_professionnelle')),
            ],
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realisation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lien du projet')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description du projet')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/services/', verbose_name='Image du service')),
                ('date_created', models.DateField(auto_now=True, null=True, verbose_name='date_created')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realiseperso', to='Resume.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Image_realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/services/', verbose_name='Image de la realisation')),
                ('date_created', models.DateField(auto_now=True, null=True, verbose_name='date_created')),
                ('realisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imgReali', to='Resume.realisation')),
            ],
        ),
        migrations.AddField(
            model_name='galerie_perso',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GaleriPerso', to='Resume.personnel'),
        ),
        migrations.AddField(
            model_name='experience_professionnelle',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ExpPro', to='Resume.personnel'),
        ),
        migrations.CreateModel(
            name='Experience_Academique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.IntegerField(blank=True, null=True, verbose_name='Année debutée')),
                ('annee_fin', models.IntegerField(blank=True, null=True, verbose_name='Année fini')),
                ('ecole', models.CharField(blank=True, max_length=50, null=True, verbose_name='Etablissement')),
                ('filiere', models.CharField(blank=True, max_length=50, null=True, verbose_name='Filière')),
                ('diplome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Diplome')),
                ('pays', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pays')),
                ('ville', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville')),
                ('staut', models.CharField(blank=True, choices=[('En cours', 'En cours'), ('Terminé', 'Terminé')], max_length=30, null=True, verbose_name='Statut')),
                ('date_created', models.DateField(auto_now=True, null=True, verbose_name='date_created')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ExpAcad', to='Resume.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(blank=True, max_length=100, null=True, verbose_name='Competence')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description de la compétence')),
                ('niveau', models.IntegerField(blank=True, null=True, verbose_name='Niveau(%)')),
                ('date_created', models.DateField(auto_now=True, null=True, verbose_name='date_created')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencesperso', to='Resume.personnel')),
            ],
        ),
    ]
