# Generated by Django 4.2.3 on 2024-03-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realisation',
            name='photo',
        ),
        migrations.AlterField(
            model_name='galerie_perso',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/Galerie/<django.db.models.fields.related.ForeignKey>/', verbose_name='Image de la realisation'),
        ),
        migrations.AlterField(
            model_name='image_realisation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/realisations/', verbose_name='Image de la realisation'),
        ),
    ]
