# Generated by Django 4.2.3 on 2024-03-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_remove_realisation_photo_alter_galerie_perso_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_proposes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/services/', verbose_name='Icone du service'),
        ),
    ]
