# Generated by Django 4.2.3 on 2024-03-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_alter_services_proposes_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galerie_perso',
            name='description',
        ),
        migrations.AddField(
            model_name='personnel',
            name='motivation',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Motivations personnelles'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='resume',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Resumé'),
        ),
    ]
