# Generated by Django 4.2.3 on 2024-03-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_personnel_description_profil_personnel_profil_actuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerie_perso',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Galerie', verbose_name='Image de la realisation'),
        ),
    ]
